Hometask for simple arrays.
Larysa33/Arrays pull request #1
Opened 2022-12-24 21:05 UTC by Larysa33

Comments for Task 2 and all additional tasks are needed. Classes: Task 1, 3 and 4 work.

2022-12-24 21:34 UTC, testershmester requested changes
Молодец, есть хорошие решения. Нехорошие надо доработать (см. комментарии)

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/Task1.java
> +        for (int i = 0; i < array.length; i++) {
может быть foreach

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/Task2.java
> +            array[i] = i;
лучше использовать random

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/Task2.java
> +            System.out.println("Обновлённый массив: " + Arrays.toString(arrayNew));
я ввела цифру 3 и результат получился неверный - [3, 0, 0, 0, 0, 0, 0, 0, 0, 0] (вместо [0, 1, 2, 4, 5, 6, 7, 8, 9])

1. длину нового массива нужно посчитать (для этого предварительно надо один раз по массиву пройтись и посчитать кол-во элементов)
2. вычислить размер нового массива
3. печать результата убрать из цикла в конец
4. исправить логическое условие на противоположное

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/additionalTasks/AdditionalTask1.java
> +            System.out.println("Введённое число не удовлетворяет условию, повторите ввод: ");
а если и второй раз число неправильное введет пользователь?

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/additionalTasks/AdditionalTask1.java
> +                arrayNew[j] = i;
idea подсказывает что может быть exception (ошибка критическая)
логика как и в Task2. пройти по массиву два раза надо - первый, чтобы узнать размер нового массива, второй - чтобы переложить элементы

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/additionalTasks/AdditionalTask2.java
> +        for (int i = 0; i%2!=0 ; i++) {
такое условие нельзя писать в том блоке i%2!=0. это условие выхода из цикла, как только встретится нечетный i, так цикл и закончится

2022-12-24 21:34 UTC, testershmester commented on src/by/teachmeskills/simpleArrays/additionalTasks/AdditionalTask2.java
> +        for (int i = 0; i%2!=0 ; i++) {
нужно просто if условие внутри цикла

2022-12-25 22:08 UTC, Larysa33 commented
@testershmester Добавила задания по многомерным массивам, вроде все работает, проверьте пожал. По одномерным массивам не знаю, как исправить, буду на уроке разбираться.

2023-01-02 20:48 UTC, Larysa33 commented
@testershmester проверьте пожал. финальные правки по массивам из последнего комита, можно перейти в этом пул-риквесте во вкладку commits и выбрать самый последний. Отдельную ветку для правок не делала в этот раз, т.к. начала вносить правки в идеи до того, как узнала про отдельную ветку.
![image](https://user-images.githubusercontent.com/47753137/210276910-2e4a666d-61ac-422e-8ae8-f49275a408f2.png)

2023-01-03 17:53 UTC, testershmester approved these changes
ок

2023-01-03 18:16 UTC, merged